### ISSUE TITLE
[macOS] nightly build failed

### ISSUE THREAD

**Issue by miaobin** [intel/webml-polyfill#845]
Nightly build failed with https://github.com/otcshare/chromium-src/commit/47194fb0fe0d01783c519e7db9bf97828a7f7fd6
```
CXX obj/content/browser/browser/gpu_process_host.o
FAILED: obj/content/browser/browser/gpu_process_host.o 

...

../../content/browser/gpu/gpu_process_host.cc:242:19: error: no member named 'kUseMkldnnForMac' in namespace 'ml::switches'
    ml::switches::kUseMkldnnForMac,
    ~~~~~~~~~~~~~~^
../../content/browser/gpu/gpu_process_host.cc:243:19: error: no member named 'kUseBNNSForMac' in namespace 'ml::switches'
    ml::switches::kUseBNNSForMac,
    ~~~~~~~~~~~~~~^
../../content/browser/gpu/gpu_process_host.cc:1124:30: error: no matching function for call to 'size'
                             base::size(kSwitchNames));
                             ^~~~~~~~~~
```
